import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises'
import { gzipSync } from 'node:zlib'

async function collect(directory, prefix = '') {
  const files = []
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const name = `${prefix}${entry.name}`
    if (entry.isDirectory()) files.push(...await collect(`${directory}/${entry.name}`, `${name}/`))
    else {
      const data = await readFile(`${directory}/${entry.name}`)
      files.push({ file: name, bytes: data.length, gzipBytes: /\.(html|css|js|svg)$/.test(name) ? gzipSync(data).length : data.length })
    }
  }
  return files.sort((a, b) => a.file.localeCompare(b.file))
}
const assets = await collect('dist')
const images = JSON.parse(await readFile('src/generated/hero-manifest.json', 'utf8'))
const base = assets.filter((asset) => !asset.file.startsWith('images/'))
const sum = (items, key) => items.reduce((total, item) => total + item[key], 0)
const select = (image, width, dpr) => image.variants.find((item) => item.width >= width * dpr) ?? image.variants.at(-1)
const scenarios = [{ width: 390, dpr: 2 }, { width: 1440, dpr: 1 }].map(({ width, dpr }) => {
  const first = select(images[0], width, dpr)
  const nextSizes = images.slice(1).map((image) => select(image, width, dpr).bytes)
  return { width, dpr, firstImage: first.src, firstImageBytes: first.bytes,
    initialRawBytes: sum(base, 'bytes') + first.bytes,
    initialGzipBytes: sum(base, 'gzipBytes') + first.bytes,
    nextImageMinBytes: Math.min(...nextSizes), nextImageMaxBytes: Math.max(...nextSizes) }
})
const report = { assets, images, scenarios, totalBytes: sum(assets, 'bytes'), totalGzipBytes: sum(assets, 'gzipBytes') }
const kib = (bytes) => `${(bytes / 1024).toFixed(2)} KiB`
const lines = [
  '# Production assets', '',
  'Generated by `npm run report:assets` after prerendering. Sizes include the final HTML, not the empty Vite template.', '',
  `Total dist: **${kib(report.totalBytes)}** raw; **${kib(report.totalGzipBytes)}** with gzip for text and unchanged binary images.`, '',
  '## HTML, CSS, JavaScript and favicon', '', '| File | Bytes | Raw | Gzip |', '|---|---:|---:|---:|',
  ...base.map((asset) => `| ${asset.file} | ${asset.bytes} | ${kib(asset.bytes)} | ${kib(asset.gzipBytes)} |`), '',
  '## Every generated hero image', '', '| Original | Variant | Dimensions | Bytes | Size |', '|---|---|---|---:|---:|',
  ...images.flatMap((image) => image.variants.map((variant) => `| ${image.original} | ${variant.src} | ${variant.width} × ${variant.height} | ${variant.bytes} | ${kib(variant.bytes)} |`)), '',
  '## Estimated initial page weight (cold cache)', '',
  'Includes HTML, CSS, JavaScript, favicon and only the deterministic first photo. Assumes sizes=100vw, the smallest adequate srcset candidate (or the largest available), and gzip HTTP compression for text. Actual negotiation/caching may differ. WebP is already compressed. No fonts or external scripts are requested.', '',
  '| Viewport / DPR | First photo | Initial raw | Initial with gzip | Next queued photo, separately |', '|---|---|---:|---:|---:|',
  ...scenarios.map((item) => `| ${item.width}px / ${item.dpr} | ${item.firstImage} | ${kib(item.initialRawBytes)} | ${kib(item.initialGzipBytes)} | ${kib(item.nextImageMinBytes)}–${kib(item.nextImageMaxBytes)} |`), '',
  'The next photo varies with shuffle and is loaded only after initial loading, when autoplay is active. It is an additional request, not included in the initial total. The whole image library is never preloaded.', '',
  'The three finish photographs are only 600px wide. All generated variants preserve this ceiling; larger originals are needed for greater desktop sharpness.', '',
]
await mkdir('reports', { recursive: true })
await writeFile('reports/assets.json', `${JSON.stringify(report, null, 2)}\n`)
await writeFile('reports/assets.md', lines.join('\n'))
console.log(`Production assets: ${kib(report.totalBytes)}; report: reports/assets.md`)
for (const item of scenarios) console.log(`${item.width}px DPR ${item.dpr}: initial ${kib(item.initialGzipBytes)} (gzip estimate), next +${kib(item.nextImageMinBytes)}–${kib(item.nextImageMaxBytes)}`)
